/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PicksRouteImport } from './routes/picks'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesArticleIdRouteImport } from './routes/articles.$articleId'

const PicksRoute = PicksRouteImport.update({
  id: '/picks',
  path: '/picks',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesArticleIdRoute = ArticlesArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => ArticlesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/packages': typeof PackagesRoute
  '/picks': typeof PicksRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/packages': typeof PackagesRoute
  '/picks': typeof PicksRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/packages': typeof PackagesRoute
  '/picks': typeof PicksRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/articles' | '/packages' | '/picks' | '/articles/$articleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/articles' | '/packages' | '/picks' | '/articles/$articleId'
  id:
    | '__root__'
    | '/'
    | '/articles'
    | '/packages'
    | '/picks'
    | '/articles/$articleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  PackagesRoute: typeof PackagesRoute
  PicksRoute: typeof PicksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/picks': {
      id: '/picks'
      path: '/picks'
      fullPath: '/picks'
      preLoaderRoute: typeof PicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$articleId': {
      id: '/articles/$articleId'
      path: '/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof ArticlesArticleIdRouteImport
      parentRoute: typeof ArticlesRoute
    }
  }
}

interface ArticlesRouteChildren {
  ArticlesArticleIdRoute: typeof ArticlesArticleIdRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesArticleIdRoute: ArticlesArticleIdRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  PackagesRoute: PackagesRoute,
  PicksRoute: PicksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
